require 'aarons_gem/rake/latex'

LatexProject.new('mascot_eco_001') { |ltx|
  ltx.copy_to = '.'
}

LatexProject.new('mascot_eco_002') { |ltx|
  ltx.add_dependency PngImage.new('../images/subconn_13contact_ethernet.png')
  ltx.add_dependency PngImage.new('../images/subconn_8contact_ethernet.png')

  ltx.add_dependency PngImage.new('../images/left_000553.png')
  ltx.add_dependency PngImage.new('../images/left_000827.png')

  ltx.add_dependency JpgImage.new('../images/mascot_desk_2.jpg')
  ltx.add_dependency JpgImage.new('../images/mascot_pool_2.jpg')

  ltx.add_dependency JpgImage.new('../images/box_POE-172.jpg')
  ltx.add_dependency JpgImage.new('../images/box_POE-171S.jpg')

  ltx.copy_to = '.'
}
